# Site settings
title: "Carlos' Reyes Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites based on resume-template.joelglovier.com"
url: https://github.com/jreyesa0901/

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Carlos Reyes"
resume_title:                   "Embedded Systems Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jreyesa0901@web.de"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "12555, Berlin"

resume_header_contact_info:     "12555, Berlin • jreyesa0901(at)web(dot)com • jreyesa0901(at)gmail(dot)com"
display_header_contact_info:    "true"

resume_header_intro: "<p>My 5+ years of experience as SW and HW developer motivates me to grow professionally in areas such as SW Testing for embedded systems (automatic integration, functional, acceptance tests), certification of industrial communication modules and assessment of systems reliability.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jreyesa0901"
  resume_twitter_url:           "https://mastodon.social/@carlosreyes_iniciativa"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/carlos-reyes-108796113/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://www.xing.com/profile/Carlos_Reyes071607/portfolio"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
